### ISSUE TITLE
charts show numbers instead of habits

### ISSUE THREAD

**Issue by jsbj** [gwensmu/daimon#10]
maybe that's on purpose? i'm going to change it locally. want me to push it? or push it to a branch so you can see it first?

**Comment by jsbj** [comment]
oh wait I think it's doing something broken – it's showing everybody's virtues

**Comment by jsbj** [comment]
oh wait oh wait maybe you already fixed it

**Comment by gwensmu** [comment]
definitely not showing what i intend it to show right now, should both show
virtue names and only virtue/practice counts for the logged-in user. I do
kind of like the idea of having all-user aggregate charts but probably with
users > 5 this particular visualization would not make sense.

**Comment by gwensmu** [comment]
this is the part where I need to start actually learning ruby to make the site work, if you can believe it

**Comment by gwensmu** [comment]
but yeah, the goal of the chart is to show total number of practices grouped by virtue title, so users can see which virtues they are currently excelling at relative to other virtues they are practicing. feel free to work on it, I was planning to return after I got some more crucial work done. (tests.)

**Comment by gwensmu** [comment]
yep this definitely reveals a big problem with how i am scoping associations between users and their data. thank you!

**Comment by gwensmu** [comment]
i was making this more complicated than it needed to be 18d3fd9dc8d7a4dcb9ffb7f280cd4cd7977b0e2c
