### ISSUE TITLE
show rates?

### ISSUE THREAD

**Issue by jsbj** [gwensmu/daimon#18]
i am curious at what rate i practice different habits ... once a day? twice a week? etc.

**Comment by gwensmu** [comment]
habit velocity. let me consider -- i worry it's too individual
habit-focused; (too taylor!)

**Comment by jsbj** [comment]
that's a good point! keeping the focus a bit more virtue-level might help
keep peoples' focus on more complex issues (how do i be a more
healthy/giving/explorative person?) rather than just gamified existence
(how many times did i press the button this week?)

2015-02-03 21:44 GMT+01:00 Gwen Smuda <notifications@github.com>:

> habit velocity. let me consider -- i worry it's too individual
> habit-focused; (too taylor!)
>
> On Tue Feb 03 2015 at 1:43:23 AM Jonah Bloch-Johnson <

**Comment by gwensmu** [comment]
cool we agree.
