### ISSUE TITLE
add labels for radio buttons?

### ISSUE THREAD

**Issue by jsbj** [gwensmu/daimon#2]
my favorite usability feature (e.g. http://www.seoconsultants.com/html/forms/labels/)

happy to do it myself if you want

**Comment by gwensmu** [comment]
a useful suggestion! go ahead and add it if you like. otherwise i'll put it on my list.

**Comment by jsbj** [comment]
ok, i tested this locally and think it should work

**Comment by gwensmu** [comment]
wonderful thank you! you are right its so much nicer to practice a habit now. (I am practicing the habit of gratitude with this very comment.)
