### ISSUE TITLE
deleting a virtue

### ISSUE THREAD

**Issue by oldwestaction** [gwensmu/daimon#5]
asks me if i am sure three times.

is this all a ploy to make me MAINTAIN MY VIRTUE

**Comment by gwensmu** [comment]
this is happening with deleting practices too.
not a ploy but you are welcome to yr own metaphysical interpretations

**Comment by gwensmu** [comment]
I think the problem is that I am including the application js like four different times in the application template. going to try reducing that to just once

**Comment by gwensmu** [comment]
yep. fixed w/ commit: 8244d57ad8de551cd344e6c11f3ca48182729954

**Comment by oldwestaction** [comment]
relatedly, i see that the same css (/assets/application-[sha].css) is being included twice... maybe something up w/ the asset pipeline?

**Comment by oldwestaction** [comment]
my b, it's not the asset pipeline -- you've just hardcoded the application css in twice (see lines 6 & 14):
https://github.com/gwensmu/daimon/blob/master/app/views/layouts/application.html.erb#L6-14

**Comment by gwensmu** [comment]
yep its true!
